apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding

metadata:
  name: {{ .Release.Name }}-admin-role-binding-backend
  namespace: backend

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-admin-service-account
    namespace: default

roleRef:
  kind: ClusterRole
  name: admin-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding

metadata:
  name: {{ .Release.Name }}-admin-role-binding-frontend
  namespace: frontend

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-admin-service-account
    namespace: default

roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
