apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRole

metadata:
  name: {{ .Release.Name }}-admin-cluster-role
  namespace: default

rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
