apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: {{ .Release.Name }}-postgres-network-policy
  namespace: backend

spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-flaskapi
      ports:
        - port: {{ .Values.postgresservice.port }}
          protocol: {{ .Values.postgresservice.protocol }}
  egress:
    - {}
