apiVersion: v1

kind: Service

metadata:
  name: {{ .Release.Name }}-postgres
  namespace: backend
  labels:
    app: {{ .Release.Name }}-postgres

spec:
  type: {{ .Values.postgresservice.type }}
  ports:
    - port: {{ .Values.postgresservice.port }}
      protocol: {{ .Values.postgresservice.protocol }}
  selector:
    app: {{ .Release.Name }}-postgres
