apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: pv-claim
  namespace: backend
  labels:
    app: {{ .Release.Name }}-postgres

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
