apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: {{ .Release.Name }}-react-app-network-policy
  namespace: frontend

spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-react-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      ports:
        - port: {{ .Values.frontendservice.port }}
          protocol: {{ .Values.frontendservice.protocol }}
  egress:
    - to:
      ports:
        - port: 80
          protocol: TCP
    - to:
      - namespaceSelector:
          matchLabels:
            name: backend
        podSelector:
          matchLabels:
            app: {{ .Release.Name }}-flaskapi
      ports:
        - port: 5000
          protocol: TCP
