apiVersion: v1

kind: Service

metadata:
  name: {{ .Release.Name }}-react-app
  namespace: frontend
  labels:
    app: {{ .Release.Name }}-react-app

spec:
  #type: {{ .Values.frontendservice.type }}
  ports:
    - port: {{ .Values.frontendservice.port }}
      protocol: {{ .Values.frontendservice.protocol }}
      targetPort: {{ .Values.frontendservice.targetPort }}
      #nodePort:  {{ .Values.frontendservice.nodePort }}
  selector:
    app: {{ .Release.Name }}-react-app
