apiVersion: v1

kind: PersistentVolume

metadata:
  name: pv-volume
  labels:
    app: postgres
    
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  # persistantVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/data"                
