apiVersion: cert-manager.io/v1

kind: Certificate

metadata:
  name: {{ .Release.Name }}-frontend-certificate
  namespace: frontend

spec:
  isCA: true
  commonName: shareyourcard.cloud
  secretName: {{ .Release.Name }}-frontend-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Release.Name }}-frontend-issuer
    kind: Issuer
    group: cert-manager.io
