apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: frontend-ingress
  namespace: frontend

spec:
  tls:
    - hosts:
        - shareyourcard.cloud
      secretName: frontend-letsencrypt-secret
  rules:
    - host: shareyourcard.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-react-app
                port:
                  number: 80
