apiVersion: cert-manager.io/v1

kind: Certificate

metadata:
  name: frontend-certificate
  namespace: frontend

spec:
  isCA: true
  commonName: shareyourcard.cloud
  secretName: frontend-letsencrypt-secret
  dnsNames:
  - shareyourcard.cloud
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: frontend-issuer
    kind: Issuer
    group: cert-manager.io
