apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: {{ .Release.Name }}-frontend-role-binding
  namespace: frontend

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-frontend-service-account
    namespace: frontend

roleRef:
  kind: Role
  name: {{ .Release.Name }}-frontend-role
  apiGroup: rbac.authorization.k8s.io
