apiVersion: cert-manager.io/v1

kind: Issuer

metadata:
  name: frontend-letsencrypt
  namespace: frontend

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zgkhhf2yhq@privaterelay.appleid.com
    privateKeySecretRef:
      name: frontend-letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
