apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: {{ .Release.Name }}-backend-role-binding
  namespace: backend

subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-backend-service-account
    namespace: backend

roleRef:
  kind: Role
  name: {{ .Release.Name }}-backend-role
  apiGroup: rbac.authorization.k8s.io
