apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:
  name: backend-role
  namespace: backend

rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "endpoints", "jobs", "deployments", "services", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
