apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: backend-role-binding
  namespace: backend

subjects:
  - kind: ServiceAccount
    name: backend-service-account
    namespace: backend

roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
