apiVersion: cert-manager.io/v1

kind: Certificate

metadata:
  name: {{ .Release.Name }}-backend-certificate
  namespace: backend

spec:
  isCA: true
  commonName: api.shareyourcard.cloud
  secretName: {{ .Release.Name }}-backend-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Release.Name }}-backend-issuer
    kind: Issuer
    group: cert-manager.io
