apiVersion: cert-manager.io/v1

kind: Certificate

metadata:
  name: backend-certificate
  namespace: backend

spec:
  isCA: true
  commonName: api.shareyourcard.cloud
  secretName: backend-tls-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: backend-issuer
    kind: Issuer
    group: cert-manager.io
