apiVersion: cert-manager.io/v1

kind: Issuer

metadata:
  name: backend-letsencrypt
  namespace: backend

spec: 
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: zgkhhf2yhq@privaterelay.appleid.com 
    privateKeySecretRef: 
      name: backend-letsencrypt 
    solvers: 
    - http01: 
        ingress: 
          class: nginx
