apiVersion: cert-manager.io/v1

kind: Issuer

metadata:
  name: backend-letsencrypt-issuer
spec: 
  acme: 
    server: https://acme-staging-v02.api.letsencrypt.org/directory 
    email: zgkhhf2yhq@privaterelay.appleid.com 
    privateKeySecretRef: 
      name: backend-letsencrypt-secret
    solvers: 
    - http01: 
        ingress: 
          class: nginx
