apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: backend-ingress
  namespace: backend

spec:
  tls:
    - hosts:
        - api.shareyourcard.cloud
      secretName: backend-tls-secret
  rules:
    - host: api.shareyourcard.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-flaskapi
                port:
                  number: 5000
