apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: {{ .Release.Name }}-flaskapi-network-policy
  namespace: backend

spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-flaskapi
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: frontend
        podSelector:
          matchLabels:
            app: {{ .Release.Name }}-react-app
      ports:
        - port: 5000
          protocol: TCP
# because of how we did the front end
    - from:
      ports:
        - port: {{ .Values.flaskapiservice.port }}
          protocol: {{ .Values.flaskapiservice.protocol }}
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: {{ .Release.Name }}-postgres
      ports:
        - port: {{ .Values.postgresservice.port }}
          protocol: {{ .Values.postgresservice.protocol }}
 # FINALLY SOLVED THE DB HOSTNAME RESOLUTION HELL YEA!!
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
