apiVersion: apps/v1

kind: Deployment

metadata:
  name: {{ .Release.Name }}-postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
      - name: {{ .Release.Name }}-postgres
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-db-config
              key: dbuser
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-db-config
              key: dbname
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pv-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim
