apiVersion: v1

kind: Service

metadata:
  name: {{ .Release.Name }}-react-app
  labels:
    app: {{ .Release.Name }}-react-app

spec:
  type: {{ .Values.frontendservice.type }}
  ports:
    - port: {{ .Values.frontendservice.port }}
      targetPort: {{ .Values.frontendservice.targetPort }}
      protocol: TCP
      nodePort:  {{ .Values.frontendservice.nodePort }}
  selector:
    app: {{ .Release.Name }}-react-app
