apiVersion: apps/v1

kind: Deployment

metadata:
  name: flaskapi
  labels:
    app: flaskapi

spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: zelyior/flask-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
