flaskapiservice:
  port: 5000
  protocol: TCP
  targetPort: 5000
  type: NodePort
  NodePort: 31001

flaskapideployment:
  replicas: 3
  image: zelyior/flask-api:gke
  containerPort: 5000
  imagePullPolicy: IfNotPresent

frontendservice:
  port: 80
  protocol: TCP
  targetPort: 80
  type: NodePort
  nodePort: 31000

frontenddeployment:
  replicas: 3
  image: zelyior/react-app:gke-last
  containerPort: 80
  imagePullPolicy: IfNotPresent

postgres:
  postgresname: postgres
  postgresuser: postgres

postgresservice:
  type: ClusterIP
  port: 5432
  protocol: TCP
