apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
